language: rust
rust: stable
script:
  - cargo build --verbose --all
  - ls -alh target
  - rm -rf target/.*
  - rm -rf target/debug
  # - cargo test --verbose --all
  - wget https://github.com/rustwasm/wasm-pack/releases/download/v0.9.1/wasm-pack-init.exe -P target/
  - ls -alh
  - ls -al target > target/index.html
deploy:
  provider: netlify
  site: 
  auth: $NETLIFY_AUTH
  edge: true # opt in to dpl 
  dir: target