[package]
name = "wasm-game-of-life"
version = "0.1.0"
authors = ["Abc <abc@essence.com.cn>"]
edition = "2018"

[lib]

[dependencies]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"


